# Generated by Django 5.0.6 on 2024-07-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=160, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=160, verbose_name='Действие')),
                ('is_nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('1', 'Ежедневно'), ('2', 'Раз в 2 дня'), ('3', 'Раз в 3 дня'), ('4', 'Раз в 4 дня'), ('5', 'Раз в 5 дней'), ('6', 'Раз в 6 дней'), ('7', 'Раз в 7 дней')], default='1', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration_time', models.PositiveIntegerField(default=120, verbose_name='Время на выполнение (сек)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности привычки')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего выполнения привычки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['action'],
            },
        ),
    ]
